Traceback (most recent call last):
  File "/home/pengs/miniconda3/envs/asapdiscovery/bin/asap-docking", line 8, in <module>
    sys.exit(docking())
  File "/home/pengs/miniconda3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/pengs/miniconda3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/pengs/miniconda3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pengs/miniconda3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pengs/miniconda3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/lila/home/pengs/asapdiscovery/asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/cli.py", line 266, in cross_docking
    cross_docking_workflow(inputs)
  File "/lila/home/pengs/asapdiscovery/asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/cross_docking.py", line 149, in cross_docking_workflow
    prepped_complexes = prepper.prep(
  File "/lila/home/pengs/asapdiscovery/asapdiscovery-modeling/asapdiscovery/modeling/protein_prep.py", line 121, in prep
    cached_complexs = ProteinPrepperBase.load_cache(cache_dir=cache_dir)
  File "/lila/home/pengs/asapdiscovery/asapdiscovery-modeling/asapdiscovery/modeling/protein_prep.py", line 217, in load_cache
    prepped_complexes.append(PreppedComplex.from_json_file(complex_file))
  File "/lila/home/pengs/asapdiscovery/asapdiscovery-data/asapdiscovery/data/schema/schema_base.py", line 60, in from_json_file
    return cls.parse_file(str(file))
  File "pydantic/main.py", line 569, in pydantic.main.BaseModel.parse_file
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for PreppedComplex
target
  value is not a valid dict (type=type_error.dict)
ligand
  field required (type=value_error.missing)
